name: Trumpkin
favicon: null
layout_spectrum: 0.9289722659159452
typography_spectrum: 0.5248718650545925
title: Trumpkin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.694599554175511
  lightness: 0.6983273939695209
  saturation: 0.8733127284795046
  rhythmicContrast: 0.9042395281139761
purpose: []
